<?php

namespace Okapi\CodeTransformer\Service\Cache;

use Okapi\CodeTransformer\Service\Options;
use Okapi\Path\Path;

/**
 * # Cache Paths
 *
 * The `CachePaths` class is responsible for generating the cache paths for
 * the different types of files that are generated by the Code Transformer.
 */
class CachePaths
{
    /**
     * # Default cache directory.
     *
     * This directory is used if no cache directory is provided.
     */
    public const DEFAULT_CACHE_DIR = 'cache/code-transformer';

    /**
     * # Directory of the transformed classes.
     *
     * This directory creates an exact copy of the original file structure.
     *
     * The transformed class has all the transformations applied to it.
     */
    public const TRANSFORMED_DIR = 'transformed';

    /**
     * Name of the file with cache paths.
     */
    public const CACHE_FILE_NAME = 'cache_states.php';

    /**
     * Get the file path for a transformed file.
     *
     * @param string $filePath
     *
     * @return string
     */
    public static function getTransformedCachePath(string $filePath): string
    {
        return self::appendToCachePath($filePath, self::TRANSFORMED_DIR);
    }

    /**
     * Append a path to the cache path.
     *
     * @param string $file
     * @param string $append
     *
     * @return string
     *
     * @noinspection PhpSameParameterValueInspection For okapi/aop
     */
    private static function appendToCachePath(string $file, string $append): string
    {
        // Append the string to the cache dir
        $newDir = Path::join(Options::$cacheDir, $append);

        return Path::resolve(
            str_replace(Options::$appDir, $newDir, $file),
        );
    }

    /**
     * Get the file path for the cache file.
     *
     * @return string
     */
    public static function getCacheFilePath(): string
    {
        return Path::join(Options::$cacheDir, self::CACHE_FILE_NAME);
    }
}
