<?php
/** @noinspection PhpPropertyOnlyWrittenInspection */
namespace Okapi\CodeTransformer\Core\Cache;

use DI\Attribute\Inject;
use Okapi\CodeTransformer\Core\Options;
use Okapi\Path\Path;

/**
 * # Cache Paths
 *
 * This class is responsible for generating the cache paths for the different
 * types of files that are generated by the Code Transformer.
 */
class CachePaths
{
    // region DI

    #[Inject]
    private Options $options;

    // endregion

    /**
     * # Directory of the transformed classes.
     *
     * This directory creates an exact copy of the original file structure.
     *
     * The transformed class has all the transformations applied to it.
     *
     * @var string
     */
    private string $transformedDir = 'transformed';

    /**
     * Name of the file with cache paths.
     *
     * @var string
     */
    private string $cacheFileName = 'cache_states.php';

    /**
     * Get the file path for a transformed file.
     *
     * @param string $filePath
     *
     * @return string
     */
    public function getTransformedCachePath(string $filePath): string
    {
        return $this->appendToCachePath($filePath, $this->transformedDir);
    }

    /**
     * Append a path to the cache path.
     *
     * @param string $file
     * @param string $append
     *
     * @return string
     */
    protected function appendToCachePath(string $file, string $append): string
    {
        $appDir   = $this->options->getAppDir();
        $cacheDir = $this->options->getCacheDir();

        // Append the string to the cache dir
        $newDir = Path::join($cacheDir, $append);

        return Path::resolve(
            str_replace($appDir, $newDir, $file),
        );
    }

    /**
     * Get the file path for the cache file.
     *
     * @return string
     */
    public function getCacheFilePath(): string
    {
        $cacheDir = $this->options->getCacheDir();

        return Path::join($cacheDir, $this->cacheFileName);
    }
}
